CREATE TYPE user_role AS ENUM ('Student', 'Administrator');
CREATE TYPE task_status_type AS ENUM ('NotStarted', 'InProgress', 'Completed');

CREATE TABLE "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE courses (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(120) NOT NULL,
    description character varying(1000) NOT NULL,
    professor_name character varying(120) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_courses" PRIMARY KEY (id)
);

CREATE TABLE identity_roles (
    id text NOT NULL,
    name character varying(256),
    normalized_name character varying(256),
    concurrency_stamp text,
    CONSTRAINT "PK_identity_roles" PRIMARY KEY (id)
);

CREATE TABLE users (
    id text NOT NULL,
    full_name character varying(120) NOT NULL,
    email character varying(256),
    password_hash text,
    role character varying(32) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_name character varying(256),
    normalized_user_name character varying(256),
    normalized_email character varying(256),
    email_confirmed boolean NOT NULL DEFAULT FALSE,
    security_stamp text,
    concurrency_stamp text,
    phone_number text,
    phone_number_confirmed boolean NOT NULL DEFAULT FALSE,
    two_factor_enabled boolean NOT NULL DEFAULT FALSE,
    lockout_end timestamp with time zone,
    lockout_enabled boolean NOT NULL DEFAULT TRUE,
    access_failed_count integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_users" PRIMARY KEY (id),
    CONSTRAINT ck_users_role CHECK (role IN ('Student', 'Administrator'))
);

CREATE TABLE study_tasks (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    course_id integer NOT NULL,
    title character varying(160) NOT NULL,
    description character varying(2000) NOT NULL,
    deadline date NOT NULL,
    status character varying(32) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_study_tasks" PRIMARY KEY (id),
    CONSTRAINT ck_study_tasks_status CHECK (status IN ('NotStarted', 'InProgress', 'Completed')),
    CONSTRAINT "FK_study_tasks_courses_course_id" FOREIGN KEY (course_id)
        REFERENCES courses (id) ON DELETE CASCADE
);

CREATE TABLE identity_role_claims (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    role_id text NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT "PK_identity_role_claims" PRIMARY KEY (id),
    CONSTRAINT "FK_identity_role_claims_identity_roles_role_id" FOREIGN KEY (role_id)
        REFERENCES identity_roles (id) ON DELETE CASCADE
);

CREATE TABLE identity_user_claims (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id text NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT "PK_identity_user_claims" PRIMARY KEY (id),
    CONSTRAINT "FK_identity_user_claims_users_user_id" FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE identity_user_logins (
    login_provider character varying(128) NOT NULL,
    provider_key character varying(128) NOT NULL,
    provider_display_name text,
    user_id text NOT NULL,
    CONSTRAINT "PK_identity_user_logins" PRIMARY KEY (login_provider, provider_key),
    CONSTRAINT "FK_identity_user_logins_users_user_id" FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE identity_user_roles (
    user_id text NOT NULL,
    role_id text NOT NULL,
    CONSTRAINT "PK_identity_user_roles" PRIMARY KEY (user_id, role_id),
    CONSTRAINT "FK_identity_user_roles_identity_roles_role_id" FOREIGN KEY (role_id)
        REFERENCES identity_roles (id) ON DELETE CASCADE,
    CONSTRAINT "FK_identity_user_roles_users_user_id" FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE identity_user_tokens (
    user_id text NOT NULL,
    login_provider character varying(128) NOT NULL,
    name character varying(128) NOT NULL,
    value text,
    CONSTRAINT "PK_identity_user_tokens" PRIMARY KEY (user_id, login_provider, name),
    CONSTRAINT "FK_identity_user_tokens_users_user_id" FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE student_courses (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    student_id text NOT NULL,
    course_id integer NOT NULL,
    assigned_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_student_courses" PRIMARY KEY (id),
    CONSTRAINT "FK_student_courses_courses_course_id" FOREIGN KEY (course_id)
        REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT "FK_student_courses_users_student_id" FOREIGN KEY (student_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT "AK_student_courses_student_id_course_id" UNIQUE (student_id, course_id)
);

CREATE TABLE student_task_statuses (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    student_id text NOT NULL,
    task_id integer NOT NULL,
    status character varying(32) NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_student_task_statuses" PRIMARY KEY (id),
    CONSTRAINT ck_student_task_statuses_status CHECK (status IN ('NotStarted', 'InProgress', 'Completed')),
    CONSTRAINT "FK_student_task_statuses_study_tasks_task_id" FOREIGN KEY (task_id)
        REFERENCES study_tasks (id) ON DELETE CASCADE,
    CONSTRAINT "FK_student_task_statuses_users_student_id" FOREIGN KEY (student_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT "AK_student_task_statuses_student_id_task_id" UNIQUE (student_id, task_id)
);

CREATE UNIQUE INDEX role_name_index ON identity_roles (normalized_name);
CREATE INDEX "IX_identity_role_claims_role_id" ON identity_role_claims (role_id);
CREATE INDEX "IX_identity_user_claims_user_id" ON identity_user_claims (user_id);
CREATE INDEX "IX_identity_user_logins_user_id" ON identity_user_logins (user_id);
CREATE INDEX "IX_identity_user_roles_role_id" ON identity_user_roles (role_id);
CREATE INDEX email_index ON users (normalized_email);
CREATE UNIQUE INDEX user_name_index ON users (normalized_user_name);
CREATE INDEX "IX_study_tasks_course_id" ON study_tasks (course_id);
CREATE INDEX "IX_study_tasks_deadline" ON study_tasks (deadline);
CREATE INDEX "IX_study_tasks_status" ON study_tasks (status);
CREATE INDEX "IX_student_courses_course_id" ON student_courses (course_id);
CREATE UNIQUE INDEX "IX_student_courses_student_id_course_id" ON student_courses (student_id, course_id);
CREATE INDEX "IX_student_task_statuses_status" ON student_task_statuses (status);
CREATE UNIQUE INDEX "IX_student_task_statuses_student_id_task_id" ON student_task_statuses (student_id, task_id);
CREATE INDEX "IX_student_task_statuses_task_id" ON student_task_statuses (task_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260601180833_InitialPostgresCreate', '9.0.1');
